### ISSUE TITLE
Kiwix-search segment failed on wikisource nopic on 32-bit system

### ISSUE THREAD

**Issue by godane** [kiwix/kiwix-tools#167]
So here is kiwix-search segment failing on searching with wikisource en nopic 2018-03 zim file. The command is 'kiwix-search -s -v wikisource_en_all_nopic_2018-03.zim heart' that i used. BTW kiwix-search and kiwix-serve work fine for other zim files. I just the wikisource ones that have this problem. This bug also happens on armhf and its proving by using nightly builds of kiwix-tools.

Here are my kiwix-tools i compiled and core file dump:
https://drive.google.com/drive/folders/1l5-lAdbByVe1oac3C7WJVX_W07Y63ih5
https://drive.google.com/file/d/1G4zhmMYAJ846pmY3ApPivptUTxAO73iV/view?usp=sharing

If this bug is 32-bit related its very limited to these zim files. Maybe the zims have a error but still work on 64-bit some how. Just not 32-bit cause of this error. Anyways its not just 32-bit i386 debian testing that has this problem since it happens on armhf debian testing too. And with your static nightly builds too.

```
root@debian:/run/initramfs/memory/data/slackware/debootstrap/squashfs-root/source# gdb --args kiwix-search -s -v wikisource_en_all_nopic_2018-03.zim heart
GNU gdb (Debian 7.12-6+b1) 7.12.0.20161007-git
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "i686-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from kiwix-search...done.
(gdb) run
Starting program: /usr/local/bin/kiwix-search -s -v wikisource_en_all_nopic_2018-03.zim heart
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/i386-linux-gnu/libthread_db.so.1".
Performing suggestion query `heart`

Program received signal SIGSEGV, Segmentation fault.
0xb7ce2e22 in ?? () from /lib/i386-linux-gnu/libc.so.6
(gdb) backtrace full
#0  0xb7ce2e22 in ?? () from /lib/i386-linux-gnu/libc.so.6
No symbol table info available.
#1  0xb7ce1075 in ?? () from /lib/i386-linux-gnu/libc.so.6
No symbol table info available.
#2  0xb770166d in zim::BufferReader::read (this=0x43f320, 
    dest=0xbfffe7c4 "\030\343g\267\b\340\272", <incomplete sequence \313>, 
    offset=..., size=...) at ../src/file_reader.cpp:364
No locals.
#3  0xb76e8bfe in zim::Reader::read<unsigned int> (this=0x43f320, offset=...)
    at ../src/file_reader.h:46
        tmp_buf = "\030\343g\267"
#4  0xb76e7daa in zim::Cluster::read_header<unsigned int> (this=0x4bb950)
    at ../src/cluster.cpp:62
        offset = 4962640
        n_offset = 3077931008
        data_address = {<REAL_TYPEDEF<unsigned long long>> = {
            v = 1}, <No data fields>}
        buffer = <error reading variable: Cannot access memory at address 0x5>
        current = {<REAL_TYPEDEF<unsigned long long>> = {
            v = 13257792429194289728}, <No data fields>}
#5  0xb76e6b42 in zim::Cluster::Cluster (this=0x4bb950, 
    reader_=<error reading variable: Cannot access memory at address 0x5>, 
    comp=zim::zimcompNone, isExtended=false) at ../src/cluster.cpp:49
---Type <return> to continue, or q <return> to quit---
        d = {<REAL_TYPEDEF<unsigned long long>> = {v = 3675}, <No data fields>}
        d1 = {<REAL_TYPEDEF<unsigned long long>> = {
            v = 13258156646712062392}, <No data fields>}
#6  0xb76f33ae in zim::FileImpl::getCluster (this=0x40e480, idx=...)
    at ../src/fileimpl.cpp:359
        cluster = std::shared_ptr<zim::Cluster> (empty) = {get() = 0x0}
        clusterOffset = {<REAL_TYPEDEF<unsigned long long>> = {
            v = 3332488795}, <No data fields>}
        next_idx = {<REAL_TYPEDEF<unsigned int>> = {
            v = 8027}, <No data fields>}
        nextClusterOffset = {<REAL_TYPEDEF<unsigned long long>> = {
            v = 6750510692}, <No data fields>}
        clusterSize = {<REAL_TYPEDEF<unsigned long long>> = {
            v = 3418021897}, <No data fields>}
        comp = zim::zimcompNone
        extended = false
        reader = std::shared_ptr<const zim::Reader> (use count 3, weak count 0) = {get() = 0x43f320}
#7  0xb76f3620 in zim::FileImpl::getBlobOffset (this=0x40e480, clusterIdx=..., 
    blobIdx=...) at ../src/fileimpl.cpp:377
        cluster = std::shared_ptr<const zim::Cluster> (use count -1010172835, weak count 1407551828) = {get() = 0xbfffea58}
#8  0xb76e4b6f in zim::Article::getOffset (this=0xbfffebe8)
---Type <return> to continue, or q <return> to quit---
    at ../src/article.cpp:204
        dirent = std::shared_ptr<const zim::Dirent> (use count 2, weak count 0) = {get() = 0x41231c}
#9  0xb7707816 in zim::Search::begin (this=0x4dc7d0) at ../src/search.cpp:252
        xapianArticle = {file = 
    std::shared_ptr<zim::FileImpl> (use count 2, weak count 0) = {
            get() = 0x40e480}, idx = 2179775}
        zimfile = 0x40e470
        dbOffset = 13215522801094346768
        databasefd = -1209367758
        database = <incomplete type>
        it = 0x40e470
        first = true
        language = ""
        stopwords = ""
        queryParser = 0xb7f7a1e0 <std::_Vector_base<zim::File const*, std::allocator<zim::File const*> >::~_Vector_base()+12>
        prefix = ""
        flags = 5097424
        query = {internal = {px = 0xb7ba501a}, static MatchNothing = {
            internal = {px = 0x0}, 
            static MatchNothing = <same as static member of an already seen type>, static MatchAll = {internal = {px = 0x409b70}, 
---Type <return> to continue, or q <return> to quit---
              static MatchNothing = <same as static member of an already seen type>, static MatchAll = <same as static member of an already seen type>}}, 
          static MatchAll = <same as static member of an already seen type>}
        enquire = {internal = {px = 0xb7baecc8}, 
          static INCLUDE_QUERY_TERMS = 1, static USE_EXACT_TERMFREQ = 2}
        keyMaker = 0xb7fa9000
#10 0xb7f77b48 in kiwix::Searcher::suggestions (this=0x412080, search="heart", 
    verbose=true) at ../src/searcher.cpp:304
        zims = std::vector of length 1, capacity 1 = {0x40e470}
        search = 0x4dc7d0
        unaccentedSearch = "heart"
#11 0x0040156c in main (argc=5, argv=0xbffff144)
    at ../src/searcher/kiwix-search.cpp:117
        searchString = "heart"
        p_result = 0xffff
        zimPath = 0xbffff306 "wikisource_en_all_nopic_2018-03.zim"
        search = 0xbffff32a "heart"
        verboseFlag = true
        suggestionFlag = true
        option_index = 0
        c = -1
        searcher = 0x412080
        reader = 0x40e3f0
(gdb) info registers
eax            0xe5b	3675
ecx            0x4	4
edx            0xbfffe7c4	-1073748028
ebx            0x404000	4210688
esp            0xbfffef80	0xbfffef80
ebp            0xbffff098	0xbffff098
esi            0x404000	4210688
edi            0x412080	4268160
eip            0x40156c	0x40156c <main(int, char**)+1114>
eflags         0x10287	[ CF PF SF IF RF ]
cs             0x73	115
ss             0x7b	123
ds             0x7b	123
es             0x7b	123
fs             0x0	0
gs             0x33	51
(gdb) x/16i $pc
=> 0x40156c <main(int, char**)+1114>:	add    $0x10,%esp
   0x40156f <main(int, char**)+1117>:	
    jmp    0x401591 <main(int, char**)+1151>
   0x401571 <main(int, char**)+1119>:	movzbl -0x21(%ebp),%eax
   0x401575 <main(int, char**)+1123>:	sub    $0xc,%esp
   0x401578 <main(int, char**)+1126>:	push   %eax
   0x401579 <main(int, char**)+1127>:	push   $0xa
   0x40157b <main(int, char**)+1129>:	push   $0x0
   0x40157d <main(int, char**)+1131>:	lea    -0xf4(%ebp),%eax
   0x401583 <main(int, char**)+1137>:	push   %eax
   0x401584 <main(int, char**)+1138>:	pushl  -0x2c(%ebp)
   0x401587 <main(int, char**)+1141>:	mov    %esi,%ebx
   0x401589 <main(int, char**)+1143>:	
    call   0x400e30 <_ZN5kiwix8Searcher6searchERNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEjjb@plt>
   0x40158e <main(int, char**)+1148>:	add    $0x20,%esp
   0x401591 <main(int, char**)+1151>:	sub    $0xc,%esp
   0x401594 <main(int, char**)+1154>:	pushl  -0x2c(%ebp)
   0x401597 <main(int, char**)+1157>:	mov    %esi,%ebx
(gdb) thread apply all backtrace

Thread 1 (Thread 0xb5939740 (LWP 11599)):
#0  0xb7ce2e22 in ?? () from /lib/i386-linux-gnu/libc.so.6
#1  0xb7ce1075 in ?? () from /lib/i386-linux-gnu/libc.so.6
#2  0xb770166d in zim::BufferReader::read (this=0x43f320, 
    dest=0xbfffe7c4 "\030\343g\267\b\340\272", <incomplete sequence \313>, 
    offset=..., size=...) at ../src/file_reader.cpp:364
#3  0xb76e8bfe in zim::Reader::read<unsigned int> (this=0x43f320, offset=...)
    at ../src/file_reader.h:46
#4  0xb76e7daa in zim::Cluster::read_header<unsigned int> (this=0x4bb950)
    at ../src/cluster.cpp:62
#5  0xb76e6b42 in zim::Cluster::Cluster (this=0x4bb950, 
    reader_=<error reading variable: Cannot access memory at address 0x5>, 
    comp=zim::zimcompNone, isExtended=false) at ../src/cluster.cpp:49
#6  0xb76f33ae in zim::FileImpl::getCluster (this=0x40e480, idx=...)
    at ../src/fileimpl.cpp:359
#7  0xb76f3620 in zim::FileImpl::getBlobOffset (this=0x40e480, clusterIdx=..., 
    blobIdx=...) at ../src/fileimpl.cpp:377
#8  0xb76e4b6f in zim::Article::getOffset (this=0xbfffebe8)
    at ../src/article.cpp:204
#9  0xb7707816 in zim::Search::begin (this=0x4dc7d0) at ../src/search.cpp:252
#10 0xb7f77b48 in kiwix::Searcher::suggestions (this=0x412080, search="heart", 
    verbose=true) at ../src/searcher.cpp:304
---Type <return> to continue, or q <return> to quit---
#11 0x0040156c in main (argc=5, argv=0xbffff144)
    at ../src/searcher/kiwix-search.cpp:117

```

**Comment by mgautierfr** [comment]
@godane I've no right to access your files on google drive.
Can you change the rights to make them public ?

**Comment by godane** [comment]
I change them to be public now. I think.
