### ISSUE TITLE
prebuilded kiwix-search 0.4.0 armhf segment failed on wikisource_en_all_nopic_2018-03.zim

### ISSUE THREAD

**Issue by godane** [kiwix/kiwix-tools#172]
Used my kiwix-search and the prebuild kiwix-search in kiwix-tools 0.4.0 thats prebuild by you guys. Here is the gdb backtrace full for the prebuild one:

```
guest@debian:/run/initramfs/memory/data$ gdb --args kiwix-search -s -v wikisource_en_all_nopic_2018-03.zim heart
GNU gdb (Debian 7.12-6+b1) 7.12.0.20161007-git
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "arm-linux-gnueabihf".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from kiwix-search...done.
(gdb) run
Starting program: /usr/local/bin/kiwix-search -s -v wikisource_en_all_nopic_2018-03.zim heart
Performing suggestion query `heart`

Program received signal SIGSEGV, Segmentation fault.
0x00428444 in memcpy ()
(gdb) backtrace full
#0  0x00428444 in memcpy ()
No symbol table info available.
#1  0x000fb160 in zim::BufferReader::read (this=0xe66f58, 
    dest=0x7effec2c "X\247\017", offset=..., size=...)
    at ../../SOURCE/libzim_release/src/file_reader.cpp:364
No locals.
#2  0x000e3b28 in zim::Reader::read<unsigned int> (this=0xe66f58, offset=...)
    at ../../SOURCE/libzim_release/src/file_reader.h:46
        tmp_buf = "X\247\017"
#3  0x000e2a3c in zim::Cluster::read_header<unsigned int> (this=0xed73a0)
    at ../../SOURCE/libzim_release/src/cluster.cpp:62
        n_offset = 0
        buffer = {<std::__shared_ptr<zim::Buffer const, (__gnu_cxx::_Lock_policy)1>> = {_M_ptr = 0x7effecac, _M_refcount = {
              _M_pi = 0x7effecc4}}, <No data fields>}
        current = {<REAL_TYPEDEF<unsigned long long>> = {
            v = 4037065230511276}, <No data fields>}
        offset = 0
        data_address = {<REAL_TYPEDEF<unsigned long long>> = {
            v = 64245100081069716}, <No data fields>}
#4  0x000e1660 in zim::Cluster::Cluster (this=0xed73a0, reader_=..., 
    comp=zim::zimcompNone, isExtended=false)
    at ../../SOURCE/libzim_release/src/cluster.cpp:49
---Type <return> to continue, or q <return> to quit---
        d = {<REAL_TYPEDEF<unsigned long long>> = {v = 3675}, <No data fields>}
        d1 = {<REAL_TYPEDEF<unsigned long long>> = {
            v = 4223668}, <No data fields>}
#5  0x000ec114 in zim::FileImpl::getCluster (this=0xe4e0e0, idx=...)
    at ../../SOURCE/libzim_release/src/fileimpl.cpp:363
        clusterOffset = {<REAL_TYPEDEF<unsigned long long>> = {
            v = 3332488795}, <No data fields>}
        clusterSize = {<REAL_TYPEDEF<unsigned long long>> = {
            v = 3418021897}, <No data fields>}
        cluster = {<std::__shared_ptr<zim::Cluster, (__gnu_cxx::_Lock_policy)1>> = {_M_ptr = 0x0, _M_refcount = {_M_pi = 0x0}}, <No data fields>}
        next_idx = {<REAL_TYPEDEF<unsigned int>> = {
            v = 8027}, <No data fields>}
        nextClusterOffset = {<REAL_TYPEDEF<unsigned long long>> = {
            v = 6750510692}, <No data fields>}
        comp = zim::zimcompNone
        extended = false
        reader = {<std::__shared_ptr<zim::Reader const, (__gnu_cxx::_Lock_policy)1>> = {_M_ptr = 0xe66f58, _M_refcount = {_M_pi = 0xeeea60}}, <No data fields>}
#6  0x000ec2fc in zim::FileImpl::getBlobOffset (this=0xe4e0e0, clusterIdx=..., 
    blobIdx=...) at ../../SOURCE/libzim_release/src/fileimpl.cpp:381
        cluster = {<std::__shared_ptr<zim::Cluster const, (__gnu_cxx::_Lock_policy)1>> = {_M_ptr = 0x4072b4 <__libc_csu_fini>, _M_refcount = {
---Type <return> to continue, or q <return> to quit---
              _M_pi = 0x0}}, <No data fields>}
#7  0x000dfa74 in zim::Article::getOffset (this=0x7effefb0)
    at ../../SOURCE/libzim_release/src/article.cpp:204
        dirent = {<std::__shared_ptr<zim::Dirent const, (__gnu_cxx::_Lock_policy)1>> = {_M_ptr = 0xe51710, _M_refcount = {_M_pi = 0xe516e8}}, <No data fields>}
#8  0x0010151c in zim::Search::begin (this=0xef06c8)
    at ../../SOURCE/libzim_release/src/search.cpp:254
        xapianArticle = {
          file = {<std::__shared_ptr<zim::FileImpl, (__gnu_cxx::_Lock_policy)1>> = {_M_ptr = 0xe4e0e0, _M_refcount = {_M_pi = 0xe4e5d8}}, <No data fields>}, 
          idx = 2179775}
        zimfile = 0xe4e0d0
        dbOffset = 458429760008436
        databasefd = 2130702668
        database = {_vptr.Database = 0xeef3c0, 
          internal = {<std::_Vector_base<Xapian::Internal::intrusive_ptr<Xapian::Database::Internal>, std::allocator<Xapian::Internal::intrusive_ptr<Xapian::Database::Internal> > >> = {
              _M_impl = {<std::allocator<Xapian::Internal::intrusive_ptr<Xapian::Database::Internal> >> = {<__gnu_cxx::new_allocator<Xapian::Internal::intrusive_ptr<Xapian::Database::Internal> >> = {<No data fields>}, <No data fields>}, 
                _M_start = 0x228698
     <icu_58::CompoundTransliterator::handleTransliterate(icu_58::Replaceable&, ---Type <return> to continue, or q <return> to quit---
UTransPosition&, signed char) const+156>, _M_finish = 0x7efff0d4, 
                _M_end_of_storage = 0x5}}, <No data fields>}}
        first = true
        language = {static npos = <optimized out>, 
          _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, 
            _M_p = 0xe43418 <std::string::_Rep::_S_empty_rep_storage+12> ""}}
        stopwords = {static npos = <optimized out>, 
          _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, 
            _M_p = 0xe43418 <std::string::_Rep::_S_empty_rep_storage+12> ""}}
        queryParser = 0x7efff0e4
        flags = 2130702668
        keyMaker = 0xe66f5c
        prefix = {static npos = <optimized out>, 
          _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x0}}
        query = {internal = {px = 0x0}, static MatchNothing = {internal = {
              px = 0x0}, 
            static MatchNothing = <same as static member of an already seen type>, static MatchAll = {internal = {px = 0xe4de10}, 
              static MatchNothing = <same as static member of an already seen type>, static MatchAll = <same as static member of an already seen type>}}, 
---Type <return> to continue, or q <return> to quit---
          static MatchAll = <same as static member of an already seen type>}
        it = {_M_current = 0xedfa50}
        enquire = {internal = {px = 0x7efff090}, 
          static INCLUDE_QUERY_TERMS = 1, static USE_EXACT_TERMFREQ = 2}
#9  0x00017e10 in kiwix::Searcher::suggestions (this=0xe51448, search=..., 
    verbose=true) at ../../SOURCE/kiwix-lib_release/src/searcher.cpp:304
        zims = {<std::_Vector_base<zim::File const*, std::allocator<zim::File const*> >> = {
            _M_impl = {<std::allocator<zim::File const*>> = {<__gnu_cxx::new_allocator<zim::File const*>> = {<No data fields>}, <No data fields>}, 
              _M_start = 0xee3200, _M_finish = 0xee3204, 
              _M_end_of_storage = 0xee3204}}, <No data fields>}
        search = 0xef06c8
        unaccentedSearch = {static npos = <optimized out>, 
          _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0xed5244 "heart"}}
#10 0x0000bed8 in main (argc=5, argv=0x7efff344)
    at ../../SOURCE/kiwix-tools_release/src/searcher/kiwix-search.cpp:117
        searchString = {static npos = <optimized out>, 
          _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0xe517e4 "heart"}}
        p_result = 0x40fe70 <__internal_atexit+24>
        zimPath = 0x7efff4ec "wikisource_en_all_nopic_2018-03.zim"
---Type <return> to continue, or q <return> to quit---
        search = 0x7efff510 "heart"
        suggestionFlag = true
        option_index = 0
        c = -1
        verboseFlag = true
        searcher = 0xe51448
        reader = 0xe4e088
(gdb)
```
Here is my compiled kiwix-search gdb backtrace: 

```
guest@debian:/run/initramfs/memory/data$ gdb --args kiwix-search -s -v wikisource_en_all_nopic_2018-03.zim heart
GNU gdb (Debian 7.12-6+b1) 7.12.0.20161007-git
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "arm-linux-gnueabihf".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from kiwix-search...done.
(gdb) run
Starting program: /usr/local/bin/kiwix-search -s -v wikisource_en_all_nopic_2018-03.zim heart
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
Performing suggestion query `heart`

Program received signal SIGSEGV, Segmentation fault.
0x76d61814 in ?? () from /lib/arm-linux-gnueabihf/libc.so.6
(gdb) backtrace full
#0  0x76d61814 in ?? () from /lib/arm-linux-gnueabihf/libc.so.6
No symbol table info available.
#1  0x769f18dc in zim::BufferReader::read (this=0x460658, dest=0x7effe9d4 "", 
    offset=..., size=...) at ../src/file_reader.cpp:364
No locals.
#2  0x769e0738 in zim::Reader::read<unsigned int> (this=0x460658, offset=...)
    at ../src/file_reader.h:46
        tmp_buf = "\000\000\000"
#3  0x769dfbf0 in zim::Cluster::read_header<unsigned int> (this=0x49b7a0)
    at ../src/cluster.cpp:62
        offset = 1996378688
        n_offset = 0
        data_address = {<REAL_TYPEDEF<unsigned long long>> = {
            v = 1}, <No data fields>}
        buffer = std::shared_ptr<const zim::Buffer> (use count 510909, weak count 811) = {get() = 0x1}
        current = {<REAL_TYPEDEF<unsigned long long>> = {
            v = 18446744071411049160}, <No data fields>}
#4  0x769def24 in zim::Cluster::Cluster (this=0x49b7a0, 
    reader_=std::shared_ptr<const zim::Reader> (expired, weak count 1) = {...}, comp=zim::zimcompNone, isExtended=false) at ../src/cluster.cpp:49
        d = {<REAL_TYPEDEF<unsigned long long>> = {v = 3675}, <No data fields>}
        d1 = {<REAL_TYPEDEF<unsigned long long>> = {
---Type <return> to continue, or q <return> to quit---
            v = 18331057858281472}, <No data fields>}
#5  0x769e77e6 in zim::FileImpl::getCluster (this=0x41c948, idx=...)
    at ../src/fileimpl.cpp:363
        cluster = std::shared_ptr<zim::Cluster> (empty) = {get() = 0x0}
        clusterOffset = {<REAL_TYPEDEF<unsigned long long>> = {
            v = 3332488795}, <No data fields>}
        next_idx = {<REAL_TYPEDEF<unsigned int>> = {
            v = 8027}, <No data fields>}
        nextClusterOffset = {<REAL_TYPEDEF<unsigned long long>> = {
            v = 6750510692}, <No data fields>}
        clusterSize = {<REAL_TYPEDEF<unsigned long long>> = {
            v = 3418021897}, <No data fields>}
        comp = zim::zimcompNone
        extended = false
        reader = std::shared_ptr<const zim::Reader> (use count 3, weak count 0) = {get() = 0x460658}
#6  0x769e7946 in zim::FileImpl::getBlobOffset (this=0x41c948, clusterIdx=..., 
    blobIdx=...) at ../src/fileimpl.cpp:381
        cluster = std::shared_ptr<const zim::Cluster> (empty) = {
          get() = 0x7effec58}
#7  0x769dd774 in zim::Article::getOffset (this=0x7effed7c)
    at ../src/article.cpp:204
        dirent = std::shared_ptr<const zim::Dirent> (use count 2, weak count 0) ---Type <return> to continue, or q <return> to quit---
= {get() = 0x42052c}
#8  0x769f6524 in zim::Search::begin (this=0x4d5940) at ../src/search.cpp:254
        xapianArticle = {file = 
    std::shared_ptr<zim::FileImpl> (use count 2, weak count 0) = {
            get() = 0x41c948}, idx = 2179775}
        zimfile = 0x41c938
        dbOffset = 18580717847965776
        databasefd = 1989589108
        database = <incomplete type>
        it = 0x41c938
        first = true
        language = ""
        stopwords = ""
        queryParser = 0x0
        prefix = "\000\000\000\000(?m)^[ \\t]*([0-9A-Fa-f]+)[ \\t]+;[ \\t]*([0-9A-Fa-f]+(?:[ \\t]+[0-9A-Fa-f]+)*)[ \\t]*;\\s*(?:(SL)|(SA)|(ML)|(MA))[ \\t]*(?:#.*?)?$|^([ \\t]*(?:#.*?)?)$|^(.*?)$\000\000\000\000\\\000s\000*\000(\000[\000\060\000-\000\071\000A\000-\000F\000]\000+\000)\000\000\000\000\000(?m)^([ "...
        flags = 1996378688
        query = {internal = {px = 0x7effed9c}, static MatchNothing = {
            internal = {px = 0x0}, 
            static MatchNothing = <same as static member of an already seen type>, static MatchAll = {internal = {px = 0x418058}, 
---Type <return> to continue, or q <return> to quit---
              static MatchNothing = <same as static member of an already seen type>, static MatchAll = <same as static member of an already seen type>}}, 
          static MatchAll = <same as static member of an already seen type>}
        enquire = {internal = {px = 0x7effeda0}, 
          static INCLUDE_QUERY_TERMS = 1, static USE_EXACT_TERMFREQ = 2}
        keyMaker = 0x0
#9  0x76f835be in kiwix::Searcher::suggestions (this=0x420278, search="heart", 
    verbose=true) at ../src/searcher.cpp:304
        zims = std::vector of length 1, capacity 1 = {0x41c938}
        search = 0x4d5940
        unaccentedSearch = "heart"
#10 0x004013e4 in main (argc=5, argv=0x7efff344)
    at ../src/searcher/kiwix-search.cpp:117
        searchString = "heart"
        p_result = 0x2
        zimPath = 0x7efff4ec "wikisource_en_all_nopic_2018-03.zim"
        search = 0x7efff510 "heart"
        verboseFlag = true
        suggestionFlag = true
        option_index = 0
        c = -1
        searcher = 0x420278
        reader = 0x41c8b8
(gdb) 
```

**Comment by kelson42** [comment]
@godane Is that still a valid bug? Does that still fail with last nightly?
